-- Generated by scripts/generate-seed.mts — edit lib/catalog.ts and re-run.
begin;

insert into brands (slug, name, sort) values
  ('apple', 'Apple', 1),
  ('samsung', 'Samsung', 2),
  ('oneplus', 'OnePlus', 3),
  ('vivo', 'Vivo', 4),
  ('oppo', 'Oppo', 5),
  ('xiaomi', 'Xiaomi / Redmi', 6),
  ('realme', 'Realme', 7),
  ('motorola', 'Motorola', 8),
  ('iqoo', 'iQOO', 9),
  ('poco', 'Poco', 10);

with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-17-pro-max', 'iPhone 17 Pro Max', 2025, 'premium') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('256 GB', 118000, 0), ('512 GB', 132000, 1), ('1 TB', 146000, 2)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-17', 'iPhone 17', 2025, 'premium') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('256 GB', 66000, 0), ('512 GB', 76000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-16-pro', 'iPhone 16 Pro', 2024, 'premium') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('128 GB', 72000, 0), ('256 GB', 79000, 1), ('512 GB', 88000, 2)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-16', 'iPhone 16', 2024, 'premium') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('128 GB', 50000, 0), ('256 GB', 56000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-15', 'iPhone 15', 2023, 'premium') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('128 GB', 40000, 0), ('256 GB', 45000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-14', 'iPhone 14', 2022, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('128 GB', 30000, 0), ('256 GB', 34000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-13', 'iPhone 13', 2021, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('128 GB', 25500, 0), ('256 GB', 28500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-12', 'iPhone 12', 2020, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('64 GB', 17000, 0), ('128 GB', 19500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('apple', 'iphone-11', 'iPhone 11', 2019, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('64 GB', 12500, 0), ('128 GB', 14500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('samsung', 'galaxy-s25-ultra', 'Galaxy S25 Ultra', 2025, 'premium') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 82000, 0), ('12 GB / 512 GB', 92000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('samsung', 'galaxy-s24', 'Galaxy S24', 2024, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 36000, 0), ('8 GB / 256 GB', 40000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('samsung', 'galaxy-s23-fe', 'Galaxy S23 FE', 2023, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 20000, 0), ('8 GB / 256 GB', 23000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('samsung', 'galaxy-a55-5g', 'Galaxy A55 5G', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 16500, 0), ('8 GB / 256 GB', 18500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('samsung', 'galaxy-a35-5g', 'Galaxy A35 5G', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 13500, 0), ('8 GB / 256 GB', 15000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('samsung', 'galaxy-m35-5g', 'Galaxy M35 5G', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('6 GB / 128 GB', 8500, 0), ('8 GB / 128 GB', 9500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('samsung', 'galaxy-f15-5g', 'Galaxy F15 5G', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('4 GB / 128 GB', 5500, 0), ('6 GB / 128 GB', 6500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oneplus', 'oneplus-13', 'OnePlus 13', 2025, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 46000, 0), ('16 GB / 512 GB', 52000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oneplus', 'oneplus-12', 'OnePlus 12', 2024, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 34000, 0), ('16 GB / 512 GB', 38500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oneplus', 'oneplus-12r', 'OnePlus 12R', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 22000, 0), ('16 GB / 256 GB', 25500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oneplus', 'oneplus-nord-4', 'OnePlus Nord 4', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 16000, 0), ('12 GB / 256 GB', 18500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oneplus', 'oneplus-nord-ce-4', 'OnePlus Nord CE 4', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 12500, 0), ('8 GB / 256 GB', 14000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oneplus', 'oneplus-nord-ce-3-lite', 'OnePlus Nord CE 3 Lite', 2023, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 8000, 0), ('8 GB / 256 GB', 9000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('vivo', 'vivo-x200', 'Vivo X200', 2024, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 42000, 0), ('16 GB / 512 GB', 48000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('vivo', 'vivo-v40', 'Vivo V40', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 20000, 0), ('12 GB / 256 GB', 23500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('vivo', 'vivo-v29', 'Vivo V29', 2023, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 13500, 0), ('12 GB / 256 GB', 16000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('vivo', 'vivo-t3-5g', 'Vivo T3 5G', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 10500, 0), ('8 GB / 256 GB', 12000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('vivo', 'vivo-y28s-5g', 'Vivo Y28s 5G', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('4 GB / 128 GB', 5500, 0), ('6 GB / 128 GB', 6500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oppo', 'oppo-find-x8', 'Oppo Find X8', 2024, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 40000, 0), ('16 GB / 512 GB', 46000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oppo', 'oppo-reno-12-pro', 'Oppo Reno 12 Pro', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 20000, 0), ('12 GB / 512 GB', 23000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oppo', 'oppo-f27-pro-plus', 'Oppo F27 Pro+', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 13000, 0), ('8 GB / 256 GB', 14500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('oppo', 'oppo-a79-5g', 'Oppo A79 5G', 2023, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 7000, 0)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('xiaomi', 'xiaomi-14', 'Xiaomi 14', 2024, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 512 GB', 34000, 0)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('xiaomi', 'redmi-note-14-pro-plus', 'Redmi Note 14 Pro+', 2025, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 256 GB', 18500, 0), ('12 GB / 512 GB', 21500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('xiaomi', 'redmi-note-13-pro', 'Redmi Note 13 Pro', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 12500, 0), ('8 GB / 256 GB', 14000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('xiaomi', 'redmi-note-12-pro', 'Redmi Note 12 Pro', 2023, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('6 GB / 128 GB', 8500, 0), ('8 GB / 256 GB', 10000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('xiaomi', 'redmi-13-5g', 'Redmi 13 5G', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('6 GB / 128 GB', 6000, 0), ('8 GB / 128 GB', 7000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('realme', 'realme-gt-7-pro', 'Realme GT 7 Pro', 2024, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 34000, 0), ('16 GB / 512 GB', 39000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('realme', 'realme-13-pro-plus', 'Realme 13 Pro+', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 256 GB', 17000, 0), ('12 GB / 512 GB', 20000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('realme', 'realme-11-pro', 'Realme 11 Pro', 2023, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 10000, 0), ('8 GB / 256 GB', 11500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('realme', 'realme-narzo-70-pro', 'Realme Narzo 70 Pro', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 8500, 0), ('8 GB / 256 GB', 9500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('motorola', 'motorola-edge-50-pro', 'Motorola Edge 50 Pro', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 256 GB', 16000, 0), ('12 GB / 256 GB', 18000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('motorola', 'moto-g85-5g', 'Moto G85 5G', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 8500, 0), ('12 GB / 256 GB', 10000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('motorola', 'moto-g64-5g', 'Moto G64 5G', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 7000, 0), ('12 GB / 256 GB', 8000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('iqoo', 'iqoo-13', 'iQOO 13', 2024, 'flagship') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('12 GB / 256 GB', 38000, 0), ('16 GB / 512 GB', 43000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('iqoo', 'iqoo-neo-9-pro', 'iQOO Neo 9 Pro', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 256 GB', 19000, 0), ('12 GB / 256 GB', 21000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('iqoo', 'iqoo-z9-5g', 'iQOO Z9 5G', 2024, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 128 GB', 9000, 0), ('8 GB / 256 GB', 10000, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('poco', 'poco-f6', 'Poco F6', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 256 GB', 17500, 0), ('12 GB / 512 GB', 20500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('poco', 'poco-x6-pro', 'Poco X6 Pro', 2024, 'mid') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('8 GB / 256 GB', 13500, 0), ('12 GB / 512 GB', 15500, 1)) as v(label, base_price, sort);
with m as (insert into models (brand_slug, slug, name, year, tier) values ('poco', 'poco-m6-pro-5g', 'Poco M6 Pro 5G', 2023, 'budget') returning id)
insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ('6 GB / 128 GB', 5500, 0), ('8 GB / 256 GB', 6500, 1)) as v(label, base_price, sort);

insert into condition_questions (key, title, subtitle, badge, kind, sort) values ('power', 'Does the device turn on and make outgoing calls?', 'The phone must boot into the OS and detect a SIM / network.', 'Mandatory check', 'single', 0);
insert into condition_options (question_key, key, label, hint, icon, pct, multiplier, sort) values
  ('power', 'working', 'Yes, fully working', 'Powers on, touchscreen works, calls connect', 'power', null, null, 0),
  ('power', 'dead', 'No, dead / boot loop', 'Doesn''t turn on or restarts repeatedly', 'power_off', null, 0.4, 1);
insert into condition_questions (key, title, subtitle, badge, kind, sort) values ('screen', 'Screen & display condition', 'Check the screen at full brightness for yellow tint, lines or touch issues.', 'Display integrity', 'single', 1);
insert into condition_options (question_key, key, label, hint, icon, pct, multiplier, sort) values
  ('screen', 'flawless', 'Flawless display', 'No scratches, original display', 'smartphone', null, null, 0),
  ('screen', 'scratches', 'Minor scratches', '1–2 light scratches visible only under light', 'texture', -0.03, null, 1),
  ('screen', 'dead_pixels', 'Dead pixels / lines', 'Spots, green/white lines or black patches', 'blur_linear', -0.1, null, 2),
  ('screen', 'cracked', 'Cracked glass', 'Cracks or broken touch', 'broken_image', -0.16, null, 3);
insert into condition_questions (key, title, subtitle, badge, kind, sort) values ('body', 'Body & back panel', 'Frame, back glass and buttons.', 'Cosmetics', 'single', 2);
insert into condition_options (question_key, key, label, hint, icon, pct, multiplier, sort) values
  ('body', 'like_new', 'Like new', 'No dents, no discolouration', 'verified', null, null, 0),
  ('body', 'normal', 'Normal wear', 'Tiny scuffs, light edge wear', 'fingerprint', -0.02, null, 1),
  ('body', 'dented', 'Heavy dents / cracked back', 'Bent frame or broken back glass', 'warning', -0.06, null, 2);
insert into condition_questions (key, title, subtitle, badge, kind, sort) values ('faults', 'Functional faults', 'Select everything that is NOT working. Leave empty if all is fine.', 'Select all that apply', 'multi', 3);
insert into condition_options (question_key, key, label, hint, icon, pct, multiplier, sort) values
  ('faults', 'camera', 'Front / rear camera', null, 'photo_camera', -0.04, null, 0),
  ('faults', 'battery', 'Battery health below 80%', null, 'battery_alert', -0.03, null, 1),
  ('faults', 'biometric', 'Face ID / fingerprint', null, 'fingerprint', -0.05, null, 2),
  ('faults', 'charging', 'Charging port', null, 'power', -0.02, null, 3),
  ('faults', 'audio', 'Speaker / mic', null, 'volume_up', -0.02, null, 4),
  ('faults', 'wireless', 'Wi-Fi / Bluetooth', null, 'wifi', -0.02, null, 5);
insert into condition_questions (key, title, subtitle, badge, kind, sort) values ('accessories', 'Original accessories', 'Box and bill with matching IMEI increase resale value.', 'Extra bonus cash', 'multi', 4);
insert into condition_options (question_key, key, label, hint, icon, pct, multiplier, sort) values
  ('accessories', 'box', 'Original box', 'Matching IMEI', 'inventory_2', 0.015, null, 0),
  ('accessories', 'charger', 'Original charger', 'Brand adapter / cable', 'power', 0.015, null, 1),
  ('accessories', 'bill', 'Valid purchase bill', 'GST invoice', 'receipt_long', 0.015, null, 2);
insert into condition_questions (key, title, subtitle, badge, kind, sort) values ('age', 'Device age', 'Time since the phone was first purchased.', 'Warranty', 'single', 5);
insert into condition_options (question_key, key, label, hint, icon, pct, multiplier, sort) values
  ('age', 'under_3', 'Under 3 months', 'Brand warranty active', null, 0.04, null, 0),
  ('age', '3_to_11', '3 to 11 months', 'Remaining brand warranty', null, null, null, 1),
  ('age', 'over_11', 'Above 11 months', 'Out of warranty', null, -0.04, null, 2);

insert into repair_services (key, name, description, icon, badge, warranty_days, minutes, price_budget, price_mid, price_flagship, price_premium, sort) values
  ('display', 'Display replacement', 'Original & premium OLED / LCD grade screens with touch calibration', 'smartphone', '180 days warranty', 180, 45, 1499, 2799, 6999, 11999, 0),
  ('battery', 'Battery replacement', '100% capacity certified Li-ion cells', 'battery_charging_full', '90 days warranty', 90, 30, 899, 1299, 2299, 3999, 1),
  ('charging_port', 'Charging port & mic', 'Sub-board / port replacement and re-soldering', 'cable', '90 days warranty', 90, 40, 349, 549, 999, 2499, 2),
  ('camera', 'Camera & lens', 'Blur-free optics, lens glass and module replacement', 'photo_camera', 'Original sensor', 90, 40, 499, 899, 2499, 5999, 3),
  ('water_damage', 'Water damage treatment', 'Ultrasonic cleaning & board-level diagnosis', 'water_drop', 'Full diagnostics', 30, 120, 599, 799, 1299, 1999, 4),
  ('speaker_mic', 'Speaker, earpiece & mic', 'Loud ring and clear call audio restored', 'volume_up', 'Sound tested', 90, 30, 299, 449, 799, 1999, 5),
  ('fingerprint', 'Fingerprint & Face ID', 'Biometric sensor repair and calibration', 'fingerprint', 'Secure sync', 90, 60, 499, 799, 1499, null, 6),
  ('software', 'Software, updates & FRP', 'Boot loop fix, OS flashing, updates and unlock', 'settings', 'Same-day fix', 30, 60, 299, 399, 599, 999, 7),
  ('data_recovery', 'Data backup & recovery', 'Backup photos, contacts & WhatsApp; recovery from dead phones', 'cloud_sync', 'Privacy assured', 0, 90, 499, 699, 999, 1499, 8),
  ('motherboard', 'Dead phone / motherboard', 'Chip-level IC, PMIC, short-circuit and reballing repairs', 'memory', 'Advanced lab', 90, 1440, null, null, null, null, 9);

insert into products (id, brand_slug, name, variant, color, grade, battery_health, price, mrp, warranty_months, highlights, description, in_box, tint, status) values
  ('ssg-101', 'apple', 'Apple iPhone 13', '128 GB', 'Midnight', 'superb', 93, 34999, 59900, 6, array['A15 Bionic', 'Face ID OK', 'Original box']::text[], 'Single-owner iPhone 13 in superb condition. Passed our 32-point check with original display and battery.', array['Phone', 'Box', 'Type-C to Lightning cable']::text[], '#1f2a37', 'available'),
  ('ssg-102', 'samsung', 'Samsung Galaxy S22 5G', '8 GB / 128 GB', 'Phantom Black', 'superb', 91, 27499, 72999, 6, array['Snapdragon 8 Gen 1', 'Dynamic AMOLED 2X', 'Clean IMEI']::text[], 'Flagship Samsung with a flawless display and GST bill.', array['Phone', 'Box', 'Cable']::text[], '#111827', 'available'),
  ('ssg-103', 'oneplus', 'OnePlus 11R 5G', '16 GB / 256 GB', 'Sonic Black', 'good', 94, 25999, 44999, 6, array['Snapdragon 8+ Gen 1', '120 Hz AMOLED', '100 W charger']::text[], 'Micro-scratches on the frame only; screen and camera perfect.', array['Phone', '100 W charger', 'Cable']::text[], '#374151', 'available'),
  ('ssg-104', 'vivo', 'Vivo V29 5G', '8 GB / 128 GB', 'Velvet Red', 'superb', 96, 19500, 32999, 6, array['50 MP OIS camera', 'Aura ring light', '3D curved display']::text[], 'Portrait specialist in superb condition.', array['Phone', 'Box', 'Charger', 'Cable']::text[], '#7f1d1d', 'available'),
  ('ssg-105', 'xiaomi', 'Redmi Note 12 Pro 5G', '6 GB / 128 GB', 'Glacier Blue', 'superb', 95, 13999, 24999, 6, array['Sony IMX766 OIS', '120 Hz OLED', '67 W charger']::text[], 'Great value mid-ranger with 67 W fast charging.', array['Phone', '67 W charger', 'Cable']::text[], '#93c5fd', 'available'),
  ('ssg-106', 'realme', 'Realme 11 Pro 5G', '8 GB / 128 GB', 'Sunrise Beige', 'good', 92, 14200, 23999, 6, array['100 MP ProLight', 'Curved display', 'Leather back']::text[], 'Light wear on the leather back; everything works perfectly.', array['Phone', 'Charger', 'Cable']::text[], '#a16207', 'available'),
  ('ssg-107', 'apple', 'Apple iPhone 11', '64 GB', 'White', 'good', 87, 17999, 43900, 6, array['Original battery', 'Face ID active', 'Dual camera']::text[], 'Entry-level iPhone, fully tested with original parts.', array['Phone', 'Cable']::text[], '#e5e7eb', 'available'),
  ('ssg-108', 'samsung', 'Samsung Galaxy M34 5G', '6 GB / 128 GB', 'Prism Silver', 'fair', 98, 10499, 18999, 3, array['6000 mAh battery', '120 Hz sAMOLED', '50 MP no-shake']::text[], 'Visible marks on the frame, but battery is nearly new.', array['Phone', 'Cable']::text[], '#cbd5e1', 'available');

commit;
