// Regenerates supabase/seed.sql from lib/catalog.ts.
// Usage: npm run seed:generate
import { writeFileSync } from "node:fs";
import { BRANDS, CONDITION_QUESTIONS, MODELS, PRODUCTS, REPAIR_SERVICES } from "../lib/catalog.ts";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const out: string[] = ["-- Generated by scripts/generate-seed.mts — edit lib/catalog.ts and re-run.", "begin;", ""];

out.push("insert into brands (slug, name, sort) values");
out.push(BRANDS.map((b) => `  (${q(b.slug)}, ${q(b.name)}, ${b.sort})`).join(",\n") + ";", "");

for (const m of MODELS) {
  out.push(
    `with m as (insert into models (brand_slug, slug, name, year, tier) values (${q(m.brandSlug)}, ${q(m.slug)}, ${q(m.name)}, ${m.year}, ${q(m.tier)}) returning id)`,
    `insert into variants (model_id, label, base_price, sort) select m.id, v.label, v.base_price, v.sort from m, (values ${m.variants
      .map((v, i) => `(${q(v.label)}, ${v.basePrice}, ${i})`)
      .join(", ")}) as v(label, base_price, sort);`,
  );
}
out.push("");

CONDITION_QUESTIONS.forEach((cq, i) => {
  out.push(
    `insert into condition_questions (key, title, subtitle, badge, kind, sort) values (${q(cq.key)}, ${q(cq.title)}, ${q(cq.subtitle)}, ${q(cq.badge)}, ${q(cq.kind)}, ${i});`,
  );
  out.push(
    "insert into condition_options (question_key, key, label, hint, icon, pct, multiplier, sort) values\n" +
      cq.options
        .map((o, j) => `  (${q(cq.key)}, ${q(o.key)}, ${q(o.label)}, ${q(o.hint)}, ${q(o.icon)}, ${q(o.pct)}, ${q(o.multiplier)}, ${j})`)
        .join(",\n") +
      ";",
  );
});
out.push("");

out.push(
  "insert into repair_services (key, name, description, icon, badge, warranty_days, minutes, price_budget, price_mid, price_flagship, price_premium, sort) values\n" +
    REPAIR_SERVICES.map(
      (s, i) =>
        `  (${q(s.key)}, ${q(s.name)}, ${q(s.description)}, ${q(s.icon)}, ${q(s.badge)}, ${s.warrantyDays}, ${s.minutes}, ${q(s.prices.budget)}, ${q(s.prices.mid)}, ${q(s.prices.flagship)}, ${q(s.prices.premium)}, ${i})`,
    ).join(",\n") +
    ";",
  "",
);

out.push(
  "insert into products (id, brand_slug, name, variant, color, grade, battery_health, price, mrp, warranty_months, highlights, description, in_box, tint, status) values\n" +
    PRODUCTS.map(
      (p) =>
        `  (${q(p.id)}, ${q(p.brandSlug)}, ${q(p.name)}, ${q(p.variant)}, ${q(p.color)}, ${q(p.grade)}, ${p.batteryHealth}, ${p.price}, ${p.mrp}, ${p.warrantyMonths}, ${q(p.highlights)}, ${q(p.description)}, ${q(p.inBox)}, ${q(p.tint)}, ${q(p.status)})`,
    ).join(",\n") +
    ";",
  "",
  "commit;",
  "",
);

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log("Wrote supabase/seed.sql");
